export const GROCERY_LIST_REQUEST = 'GROCERY_LIST_REQUEST';
export const GROCERY_LIST_SUCCEED = 'GROCERY_LIST_SUCCEED';
export const GROCERY_LIST_FAIL = 'GROCERY_LIST_FAIL';
export const GROCERY_LIST_RESET = 'GROCERY_LIST_FAIL';

export const GROCERY_DETAILS_REQUEST = 'GROCERY_DETAILS_REQUEST';
export const GROCERY_DETAILS_SUCCEED = 'GROCERY_DETAILS_SUCCEED';
export const GROCERY_DETAILS_FAIL = 'GROCERY_DETAILS_FAIL';
export const GROCERY_DETAILS_RESET = 'GROCERY_DETAILS_FAIL';

export const GROCERY_ADD_REQUEST = 'GROCERY_ADD_REQUEST';
export const GROCERY_ADD_SUCCEED = 'GROCERY_ADD_SUCCEED';
export const GROCERY_ADD_FAIL = 'GROCERY_ADD_FAIL';
export const GROCERY_ADD_RESET = 'GROCERY_ADD_FAIL';

export const GROCERY_DELETE_REQUEST = 'GROCERY_DELETE_REQUEST';
export const GROCERY_DELETE_SUCCEED = 'GROCERY_DELETE_SUCCEED';
export const GROCERY_DELETE_FAIL = 'GROCERY_DELETE_FAIL';
export const GROCERY_DELETE_RESET = 'GROCERY_DELETE_FAIL';

export const GROCERY_DETAILS_UPDATE_REQUEST = 'GROCERY_DETAILS_UPDATE_REQUEST';
export const GROCERY_DETAILS_UPDATE_SUCCEED = 'GROCERY_DETAILS_UPDATE_SUCCEED';
export const GROCERY_DETAILS_UPDATE_FAIL = 'GROCERY_DETAILS_UPDATE_FAIL';
export const GROCERY_DETAILS_UPDATE_RESET = 'GROCERY_DETAILS_UPDATE_RESET';