export const RECIPE_LIST_REQUEST = 'RECIPE_LIST_REQUEST';
export const RECIPE_LIST_SUCCEED = 'RECIPE_LIST_SUCCEED';
export const RECIPE_LIST_FAIL = 'RECIPE_LIST_FAIL';
export const RECIPE_LIST_RESET = 'RECIPE_LIST_FAIL';

export const RECIPE_DETAILS_REQUEST = 'RECIPE_DETAILS_REQUEST';
export const RECIPE_DETAILS_SUCCEED = 'RECIPE_DETAILS_SUCCEED';
export const RECIPE_DETAILS_FAIL = 'RECIPE_DETAILS_FAIL';
export const RECIPE_DETAILS_RESET = 'RECIPE_DETAILS_FAIL';

export const RECIPE_ADD_REQUEST = 'RECIPE_ADD_REQUEST';
export const RECIPE_ADD_SUCCEED = 'RECIPE_ADD_SUCCEED';
export const RECIPE_ADD_FAIL = 'RECIPE_ADD_FAIL';
export const RECIPE_ADD_RESET = 'RECIPE_ADD_FAIL';

export const RECIPE_DELETE_REQUEST = 'RECIPE_DELETE_REQUEST';
export const RECIPE_DELETE_SUCCEED = 'RECIPE_DELETE_SUCCEED';
export const RECIPE_DELETE_FAIL = 'RECIPE_DELETE_FAIL';
export const RECIPE_DELETE_RESET = 'RECIPE_DELETE_FAIL';

export const RECIPE_DETAILS_UPDATE_REQUEST = 'RECIPE_DETAILS_UPDATE_REQUEST';
export const RECIPE_DETAILS_UPDATE_SUCCEED = 'RECIPE_DETAILS_UPDATE_SUCCEED';
export const RECIPE_DETAILS_UPDATE_FAIL = 'RECIPE_DETAILS_UPDATE_FAIL';
export const RECIPE_DETAILS_UPDATE_RESET = 'RECIPE_DETAILS_UPDATE_RESET';

export const INGREDIENT_UPDATE_REQUEST = 'INGREDIENT_UPDATE_REQUEST';
export const INGREDIENT_UPDATE_SUCCESS = 'INGREDIENT_UPDATE_SUCCESS';
export const INGREDIENT_UPDATE_FAIL = 'INGREDIENT_UPDATE_FAIL';
export const INGREDIENT_UPDATE_RESET = 'INGREDIENT_UPDATE_RESET';

export const ADD_INGREDIENT_REQUEST = 'ADD_INGREDIENT_REQUEST';
export const ADD_INGREDIENT_SUCCESS = 'ADD_INGREDIENT_SUCCESS';
export const ADD_INGREDIENT_FAIL = 'ADD_INGREDIENT_FAIL';
export const ADD_INGREDIENT_RESET = 'ADD_INGREDIENT_RESET';

export const DELETE_INGREDIENT_REQUEST = 'DELETE_INGREDIENT_REQUEST';
export const DELETE_INGREDIENT_SUCCESS = 'DELETE_INGREDIENT_SUCCESS';
export const DELETE_INGREDIENT_FAIL = 'DELETE_INGREDIENT_FAIL';
export const DELETE_INGREDIENT_RESET = 'DELETE_INGREDIENT_RESET';